version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: main-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432